### ISSUE TITLE
Attendances showing up improperly for dropped students

### ISSUE THREAD

**Issue by noloerino** [csmberkeley/csm_web#144]
A mentor reported a bug under the following circumstances:
- A student (https://scheduler.csmentors.org/admin/scheduler/student/1239/change/) dropped mid-way through the semester.
- Another student (https://scheduler.csmentors.org/admin/scheduler/student/1555/change/) added some weeks after the previous student dropped.
The attendance record of the dropped student was now being shown under the name of the newly added student, e.g. 10/21 was listed as UN for the new student despite an attendance (likely) not previously existing in the database for this new student. The mentor manually cleared all the attendances (i.e. set them to --), which, based on the admin view, seems to have PUT for the appropriate student.

I suspect that the culprit is here: https://github.com/csmberkeley/csm_web/blob/faefb0e520f8e654a823734ac234498352f52787/csm_web/scheduler/views.py#L97
since filtering on active may do weird things, but I haven't gotten the chance to test this workflow to properly reproduce the bug and test a fix. I'm leaving this issue here before I forget.

**Comment by Svetlitski** [comment]
You think this is likely still an issue? Is there a way we can write a test for it?

**Comment by noloerino** [comment]
I tried setting up some scenarios with dropped students on my own some time last semester, but couldn't figure out how to reproduce it. It's likely caused by some edge case.

**Comment by Svetlitski** [comment]
Given that this hasn't shown up again and how much both our frontend and backend have changed since this issue was reported, I'm going to mark this as closed.
