### ISSUE TITLE
Can't save new mentor for new section on admin page

### ISSUE THREAD

**Issue by noloerino** [csmberkeley/csm_web#162]
I realized a while ago that you can't create a new section on the admin page because the `mentor` field is disable to prevent a single `Mentor` from having multiple associated `Section`s by accident, so it doesn't save properly. A couple possible workarounds off the top of my head:
- Make the field not disabled, and explicitly leave a help message saying to not change the selector dropdown and use the edit/new buttons intead
- Hide the `mentor` field from the form, and have logic on the backend to either create a new `Mentor` instance or modify the existing one as necessary.

**Comment by Svetlitski** [comment]
We can now create new Sections via the Coord interface, so this is no longer an issue IMO. Re-open if you disagree and I'll work on it.
