### ISSUE TITLE
Migrate fetch requests to react-query

### ISSUE THREAD

**Issue by smartspot2** [csmberkeley/csm_web#289]
See: https://react-query.tanstack.com

With React 18, with strict mode enabled, React will mount, then unmount, then mount the component again as an additional check. Further, it is mentioned that generally it's not a good idea to fetch data in hooks, and it's better to use a third-party library to handle fetching data.

React query has a bunch of optimizations with request deduplication, caching data, etc. to make requests a lot more efficient in general.

With the migration, there should be a central query file where we store custom hooks to get query data; exceptions could be for one-off requests that will definitely not be repeated in other components. At the very least, requests to `/courses`, `/profiles`, etc should be put into this central file, as the data is usually accessed in multiple different components.

In addition, we may want to change some of the defaults with the query client: https://react-query.tanstack.com/guides/important-defaults; there may be some options that we want to enable or disable here.

This issue should be addressed only after we upgrade to React 18 along with #287, as there will be substantial changes to some component structure.

**Comment by edwardneo** [comment]
Marking as closed since this is already merged (2 years ago...)
