### ISSUE TITLE
Small Modal Size for Coordinator Blacklist Window

### ISSUE THREAD

**Issue by joshualiao** [csmberkeley/csm_web#447]
Steps to reproduce: 
1. As a coordinator, add ~6 students to section and bring it over capacity. 
2. It complains; select enroll and expand section.
3. Try removing a student using the red x on the student names.

The popup window to confirm blacklisting a student from the course is too small— you can only see "BLACKLIST" and have to scroll.

**Comment by aaudreywu** [comment]
We tried to reproduce the error, but we didn't get the same results.
![screen_shot_2023-10-30_at_7 51 08_pm_720](https://github.com/csmberkeley/csm_web/assets/40411912/9b82f65e-0aca-40e4-bf9e-bd87d40c0b0d)

**Comment by joshualiao** [comment]
Could be my local repo problem? I re-pulled and got the same thing still. See: https://github.com/csmberkeley/csm_web/issues/451#issuecomment-1786442030

**Comment by smartspot2** [comment]
Closing since I can't reproduce the issue; it's likely something with your browser, or with some weird behavior with CSS.
